import express from "express";
import { campaignRoutes } from "./campaign.routes";
import { campaignCategoryRoutes } from "./campaignCategory.routes";
import { campaignDonationRoutes } from "./campaignDonation.routes";
import { campaignGoalRoutes } from "./campaignGoal.routes";
import { campaignMediaRoutes } from "./campaignMedia.routes";
import { campaignMilestoneRoutes } from "./campaignMilestone.routes";
import { masterDonationRoutes } from "./donation.routes";
import { donationCategoryRoutes } from "./donationCategory.routes";
import { donationInstallmentRoutes } from "./donationInstallment.routes";
import { donationItemRoutes } from "./donationItem.routes";
import { donationReceiptRoutes } from "./donationReceipt.routes";
import { donationScheduleRoutes } from "./donationSchedule.routes";
import { donationTypeRoutes } from "./donationType.routes";
import { emergencyCampaignRoutes } from "./emergencyCampaign.routes";
import { expenseAttachmentRoutes } from "./expenseAttachment.routes";
import { financialReportRoutes } from "./financialReport.routes";
import { fundRoutes } from "./fund.routes";
import { fundAllocationRoutes } from "./fundAllocation.routes";
import { fundAllocationHistoryRoutes } from "./fundAllocationHistory.routes";
import { fundTransferRoutes } from "./fundTransfer.routes";
import { invoiceRoutes } from "./invoice.routes";
import { organizationRoutes } from "./organization.routes";
import { organizationProfileRoutes } from "./organizationProfile.routes";
import { branchRoutes } from "./branch.routes";
import { branchTypeRoutes } from "./branchType.routes";
import { branchSettingRoutes } from "./branchSetting.routes";
import { branchManagerRoutes } from "./branchManager.routes";
import { branchStaffRoutes } from "./branchStaff.routes";
import { regionRoutes } from "./region.routes";
import { divisionRoutes } from "./division.routes";
import { districtRoutes } from "./district.routes";
import { upazilaRoutes } from "./upazila.routes";
import { unionRoutes } from "./union.routes";
import { wardRoutes } from "./ward.routes";
import { areaCoverageRoutes } from "./areaCoverage.routes";
import { branchCoverageRoutes } from "./branchCoverage.routes";
import { branchTargetRoutes } from "./branchTarget.routes";
import { branchPerformanceRoutes } from "./branchPerformance.routes";
import { branchBudgetRoutes } from "./branchBudget.routes";
import { membershipRoutes } from "./membership.routes";
import { paymentRoutes } from "./payment.routes";
import { paymentGatewayRoutes } from "./paymentGateway.routes";
import { paymentLogRoutes } from "./paymentLog.routes";
import { paymentTransactionRoutes } from "./paymentTransaction.routes";
import { paymentWebhookRoutes } from "./paymentWebhook.routes";
import { payoutRoutes } from "./payout.routes";
import { projectRoutes } from "./project.routes";
import { projectBeneficiaryRoutes } from "./projectBeneficiary.routes";
import { projectBudgetRoutes } from "./projectBudget.routes";
import { projectCategoryRoutes } from "./projectCategory.routes";
import { projectExpenseRoutes } from "./projectExpense.routes";
import { projectGalleryRoutes } from "./projectGallery.routes";
import { projectReportRoutes } from "./projectReport.routes";
import { projectTimelineRoutes } from "./projectTimeline.routes";
import { projectUpdateRoutes } from "./projectUpdate.routes";
import { projectVolunteerRoutes } from "./projectVolunteer.routes";
import { refundRoutes } from "./refund.routes";
import { settlementRoutes } from "./settlement.routes";
import { userRoutes } from "./user.routes";

const router = express.Router();

router.use("/user", userRoutes);
router.use("/user/memberships", membershipRoutes);
router.use("/campaigns", campaignRoutes);
router.use("/campaign-categories", campaignCategoryRoutes);
router.use("/campaign-goals", campaignGoalRoutes);
router.use("/campaign-milestones", campaignMilestoneRoutes);
router.use("/campaign-media", campaignMediaRoutes);
router.use("/campaign-donations", campaignDonationRoutes);
router.use("/emergency-campaigns", emergencyCampaignRoutes);
router.use("/project-categories", projectCategoryRoutes);
router.use("/projects", projectRoutes);
router.use("/project-budgets", projectBudgetRoutes);
router.use("/project-expenses", projectExpenseRoutes);
router.use("/expense-attachments", expenseAttachmentRoutes);
router.use("/project-beneficiaries", projectBeneficiaryRoutes);
router.use("/project-volunteers", projectVolunteerRoutes);
router.use("/project-gallery", projectGalleryRoutes);
router.use("/project-updates", projectUpdateRoutes);
router.use("/project-timelines", projectTimelineRoutes);
router.use("/fund-allocations", fundAllocationRoutes);
router.use("/project-reports", projectReportRoutes);
router.use("/donation-categories", donationCategoryRoutes);
router.use("/donation-types", donationTypeRoutes);
router.use("/donations", masterDonationRoutes);
router.use("/donation-items", donationItemRoutes);
router.use("/donation-schedules", donationScheduleRoutes);
router.use("/donation-installments", donationInstallmentRoutes);
router.use("/payments", paymentRoutes);
router.use("/payment-gateways", paymentGatewayRoutes);
router.use("/payment-transactions", paymentTransactionRoutes);
router.use("/payment-webhooks", paymentWebhookRoutes);
router.use("/refunds", refundRoutes);
router.use("/donation-receipts", donationReceiptRoutes);
router.use("/invoices", invoiceRoutes);
router.use("/funds", fundRoutes);
router.use("/fund-transfers", fundTransferRoutes);
router.use("/fund-allocation-history", fundAllocationHistoryRoutes);
router.use("/settlements", settlementRoutes);
router.use("/payouts", payoutRoutes);
router.use("/financial-reports", financialReportRoutes);
router.use("/payment-logs", paymentLogRoutes);
router.use("/organizations", organizationRoutes);
router.use("/organization-profiles", organizationProfileRoutes);
router.use("/branches", branchRoutes);
router.use("/branch-types", branchTypeRoutes);
router.use("/branch-settings", branchSettingRoutes);
router.use("/branch-managers", branchManagerRoutes);
router.use("/branch-staff", branchStaffRoutes);
router.use("/regions", regionRoutes);
router.use("/divisions", divisionRoutes);
router.use("/districts", districtRoutes);
router.use("/upazilas", upazilaRoutes);
router.use("/unions", unionRoutes);
router.use("/wards", wardRoutes);
router.use("/area-coverages", areaCoverageRoutes);
router.use("/branch-coverages", branchCoverageRoutes);
router.use("/branch-targets", branchTargetRoutes);
router.use("/branch-performances", branchPerformanceRoutes);
router.use("/branch-budgets", branchBudgetRoutes);

export const RootRouter = router;
