import { configureStore } from "@reduxjs/toolkit";
import { counterSlice } from "../slices/counterSlice";

import {
  analyticsReportsApi,
  areaCoverageApi,
  beneficiaryApi,
  branchAnnouncementApi,
  branchAuditApi,
  branchBudgetApi,
  branchCoverageApi,
  branchDocumentApi,
  branchExpenseApi,
  branchFundApi,
  branchInventoryApi,
  branchManagerApi,
  branchMeetingApi,
  branchPerformanceApi,
  branchSettingApi,
  branchApi,
  branchStaffApi,
  branchTargetApi,
  branchTransferApi,
  branchTypeApi,
  branchVehicleApi,
  campaignCategoryApi,
  campaignDonationApi,
  campaignGoalApi,
  campaignMediaApi,
  campaignMilestoneApi,
  campaignCategoriesApi,
  districtApi,
  divisionApi,
  donationCategoryApi,
  donationInstallmentApi,
  donationItemApi,
  donationReceiptApi,
  donationScheduleApi,
  donationApi,
  donationTypeApi,
  donorApi,
  emergencyCampaignApi,
  eventsMediaApi,
  expenseAttachmentApi,
  financialReportApi,
  fundAllocationHistoryApi,
  fundAllocationApi,
  fundApi,
  fundTransferApi,
  invoiceApi,
  membershipApi,
  operationalZoneApi,
  organizationHierarchyApi,
  organizationProfileApi,
  organizationApi,
  paymentGatewayApi,
  paymentLogApi,
  paymentApi,
  paymentTransactionApi,
  paymentWebhookApi,
  payoutApi,
  projectBeneficiaryApi,
  projectBudgetApi,
  projectCategoryApi,
  projectExpenseApi,
  projectGalleryApi,
  projectReportApi,
  projectApi,
  projectTimelineApi,
  projectUpdateApi,
  projectVolunteerApi,
  refundApi,
  regionApi,
  regionalCoordinatorApi,
  roleApi,
  settlementApi,
  territoryAssignmentApi,
  unionApi,
  upazilaApi,
  userApi,
  volunteerApi,
  wardApi,
  zoneAssignmentApi,
} from "../slices";

const apiSlices = [
  analyticsReportsApi,
  areaCoverageApi,
  beneficiaryApi,
  branchAnnouncementApi,
  branchAuditApi,
  branchBudgetApi,
  branchCoverageApi,
  branchDocumentApi,
  branchExpenseApi,
  branchFundApi,
  branchInventoryApi,
  branchManagerApi,
  branchMeetingApi,
  branchPerformanceApi,
  branchSettingApi,
  branchApi,
  branchStaffApi,
  branchTargetApi,
  branchTransferApi,
  branchTypeApi,
  branchVehicleApi,
  campaignCategoryApi,
  campaignDonationApi,
  campaignGoalApi,
  campaignMediaApi,
  campaignMilestoneApi,
  campaignCategoriesApi,
  districtApi,
  divisionApi,
  donationCategoryApi,
  donationInstallmentApi,
  donationItemApi,
  donationReceiptApi,
  donationScheduleApi,
  donationApi,
  donationTypeApi,
  donorApi,
  emergencyCampaignApi,
  eventsMediaApi,
  expenseAttachmentApi,
  financialReportApi,
  fundAllocationHistoryApi,
  fundAllocationApi,
  fundApi,
  fundTransferApi,
  invoiceApi,
  membershipApi,
  operationalZoneApi,
  organizationHierarchyApi,
  organizationProfileApi,
  organizationApi,
  paymentGatewayApi,
  paymentLogApi,
  paymentApi,
  paymentTransactionApi,
  paymentWebhookApi,
  payoutApi,
  projectBeneficiaryApi,
  projectBudgetApi,
  projectCategoryApi,
  projectExpenseApi,
  projectGalleryApi,
  projectReportApi,
  projectApi,
  projectTimelineApi,
  projectUpdateApi,
  projectVolunteerApi,
  refundApi,
  regionApi,
  regionalCoordinatorApi,
  roleApi,
  settlementApi,
  territoryAssignmentApi,
  unionApi,
  upazilaApi,
  userApi,
  volunteerApi,
  wardApi,
  zoneAssignmentApi,
];

const apiReducers = apiSlices.reduce((acc, api) => {
  acc[api.reducerPath] = api.reducer;
  return acc;
}, {} as Record<string, any>);

export const store = configureStore({
  reducer: {
    counter: counterSlice.reducer,
    ...apiReducers,
  },
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware().concat(...(apiSlices.map((api) => api.middleware) as any[])),
});

export type RootState = ReturnType<typeof store.getState>;
export type AppDispatch = typeof store.dispatch;
